<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>PnSAPI</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
	<OutputType>Library</OutputType>
  </PropertyGroup>

	<ItemGroup>
		<Reference Include="Assembly-CSharp">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\Assembly-CSharp.dll</HintPath>
		</Reference>
		<Reference Include="BepInEx.Core">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\core\BepInEx.Core.dll</HintPath>
		</Reference>
		<Reference Include="BepInEx.Unity.IL2CPP">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\core\BepInEx.Unity.IL2CPP.dll</HintPath>
		</Reference>
		<Reference Include="Discord">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\Discord.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppInterop.Common">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\core\Il2CppInterop.Common.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppInterop.Runtime">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\core\Il2CppInterop.Runtime.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppMono.Security">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\Il2CppMono.Security.dll</HintPath>
		</Reference>
		<Reference Include="Il2Cppmscorlib">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\Il2Cppmscorlib.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppSystem">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\Il2CppSystem.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppSystem.Configuration">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\Il2CppSystem.Configuration.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppSystem.Core">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\Il2CppSystem.Core.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppSystem.Data">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\Il2CppSystem.Data.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppSystem.Drawing">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\Il2CppSystem.Drawing.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppSystem.Numerics">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\Il2CppSystem.Numerics.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppSystem.Runtime.Serialization">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\Il2CppSystem.Runtime.Serialization.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppSystem.Xml">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\Il2CppSystem.Xml.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppSystem.Xml.Linq">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\Il2CppSystem.Xml.Linq.dll</HintPath>
		</Reference>
		<Reference Include="Newtonsoft.Json">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\Newtonsoft.Json.dll</HintPath>
		</Reference>
		<Reference Include="SemanticVersioning">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\core\SemanticVersioning.dll</HintPath>
		</Reference>
		<Reference Include="unity-websocket-sharp">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\unity-websocket-sharp.dll</HintPath>
		</Reference>
		<Reference Include="Unity.Burst">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\Unity.Burst.dll</HintPath>
		</Reference>
		<Reference Include="Unity.Burst.Unsafe">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\Unity.Burst.Unsafe.dll</HintPath>
		</Reference>
		<Reference Include="Unity.Collections">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\Unity.Collections.dll</HintPath>
		</Reference>
		<Reference Include="Unity.Collections.LowLevel.ILSupport">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\Unity.Collections.LowLevel.ILSupport.dll</HintPath>
		</Reference>
		<Reference Include="Unity.InputSystem">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\Unity.InputSystem.dll</HintPath>
		</Reference>
		<Reference Include="Unity.InputSystem.ForUI">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\Unity.InputSystem.ForUI.dll</HintPath>
		</Reference>
		<Reference Include="Unity.Mathematics">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\Unity.Mathematics.dll</HintPath>
		</Reference>
		<Reference Include="Unity.Netcode.Components">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\Unity.Netcode.Components.dll</HintPath>
		</Reference>
		<Reference Include="Unity.Netcode.Runtime">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\Unity.Netcode.Runtime.dll</HintPath>
		</Reference>
		<Reference Include="Unity.Networking.Transport">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\Unity.Networking.Transport.dll</HintPath>
		</Reference>
		<Reference Include="Unity.RenderPipeline.Universal.ShaderLibrary">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\Unity.RenderPipeline.Universal.ShaderLibrary.dll</HintPath>
		</Reference>
		<Reference Include="Unity.RenderPipelines.Core.Runtime">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\Unity.RenderPipelines.Core.Runtime.dll</HintPath>
		</Reference>
		<Reference Include="Unity.RenderPipelines.Core.Runtime.Shared">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\Unity.RenderPipelines.Core.Runtime.Shared.dll</HintPath>
		</Reference>
		<Reference Include="Unity.RenderPipelines.GPUDriven.Runtime">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\Unity.RenderPipelines.GPUDriven.Runtime.dll</HintPath>
		</Reference>
		<Reference Include="Unity.RenderPipelines.Universal.Runtime">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\Unity.RenderPipelines.Universal.Runtime.dll</HintPath>
		</Reference>
		<Reference Include="Unity.Services.Authentication">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\Unity.Services.Authentication.dll</HintPath>
		</Reference>
		<Reference Include="Unity.Services.Authentication.PlayerAccounts">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\Unity.Services.Authentication.PlayerAccounts.dll</HintPath>
		</Reference>
		<Reference Include="Unity.Services.CloudCode">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\Unity.Services.CloudCode.dll</HintPath>
		</Reference>
		<Reference Include="Unity.Services.CloudCode.GeneratedBindings">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\Unity.Services.CloudCode.GeneratedBindings.dll</HintPath>
		</Reference>
		<Reference Include="Unity.Services.Core">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\Unity.Services.Core.dll</HintPath>
		</Reference>
		<Reference Include="Unity.Services.Core.Components">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\Unity.Services.Core.Components.dll</HintPath>
		</Reference>
		<Reference Include="Unity.Services.Core.Configuration">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\Unity.Services.Core.Configuration.dll</HintPath>
		</Reference>
		<Reference Include="Unity.Services.Core.Device">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\Unity.Services.Core.Device.dll</HintPath>
		</Reference>
		<Reference Include="Unity.Services.Core.Environments">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\Unity.Services.Core.Environments.dll</HintPath>
		</Reference>
		<Reference Include="Unity.Services.Core.Environments.Internal">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\Unity.Services.Core.Environments.Internal.dll</HintPath>
		</Reference>
		<Reference Include="Unity.Services.Core.Internal">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\Unity.Services.Core.Internal.dll</HintPath>
		</Reference>
		<Reference Include="Unity.Services.Core.Registration">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\Unity.Services.Core.Registration.dll</HintPath>
		</Reference>
		<Reference Include="Unity.Services.Core.Scheduler">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\Unity.Services.Core.Scheduler.dll</HintPath>
		</Reference>
		<Reference Include="Unity.Services.Core.Telemetry">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\Unity.Services.Core.Telemetry.dll</HintPath>
		</Reference>
		<Reference Include="Unity.Services.Core.Threading">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\Unity.Services.Core.Threading.dll</HintPath>
		</Reference>
		<Reference Include="Unity.Services.Lobbies">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\Unity.Services.Lobbies.dll</HintPath>
		</Reference>
		<Reference Include="Unity.Services.QoS">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\Unity.Services.QoS.dll</HintPath>
		</Reference>
		<Reference Include="Unity.Services.Relay">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\Unity.Services.Relay.dll</HintPath>
		</Reference>
		<Reference Include="Unity.Services.Vivox">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\Unity.Services.Vivox.dll</HintPath>
		</Reference>
		<Reference Include="Unity.Services.Wire.Internal">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\Unity.Services.Wire.Internal.dll</HintPath>
		</Reference>
		<Reference Include="Unity.TextMeshPro">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\Unity.TextMeshPro.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\UnityEngine.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.AccessibilityModule">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\UnityEngine.AccessibilityModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.AIModule">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\UnityEngine.AIModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.AndroidJNIModule">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\UnityEngine.AndroidJNIModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.AnimationModule">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\UnityEngine.AnimationModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.AssetBundleModule">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\UnityEngine.AssetBundleModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.AudioModule">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\UnityEngine.AudioModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.ClothModule">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\UnityEngine.ClothModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.ClusterInputModule">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\UnityEngine.ClusterInputModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.ClusterRendererModule">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\UnityEngine.ClusterRendererModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.ContentLoadModule">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\UnityEngine.ContentLoadModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.CoreModule">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\UnityEngine.CoreModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.CrashReportingModule">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\UnityEngine.CrashReportingModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.DirectorModule">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\UnityEngine.DirectorModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.DSPGraphModule">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\UnityEngine.DSPGraphModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.GameCenterModule">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\UnityEngine.GameCenterModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.GIModule">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\UnityEngine.GIModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.GraphicsStateCollectionSerializerModule">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\UnityEngine.GraphicsStateCollectionSerializerModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.GridModule">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\UnityEngine.GridModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.HierarchyCoreModule">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\UnityEngine.HierarchyCoreModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.HotReloadModule">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\UnityEngine.HotReloadModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.ImageConversionModule">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\UnityEngine.ImageConversionModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.IMGUIModule">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\UnityEngine.IMGUIModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.InputForUIModule">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\UnityEngine.InputForUIModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.InputLegacyModule">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\UnityEngine.InputLegacyModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.InputModule">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\UnityEngine.InputModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.JSONSerializeModule">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\UnityEngine.JSONSerializeModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.LocalizationModule">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\UnityEngine.LocalizationModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.MarshallingModule">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\UnityEngine.MarshallingModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.MultiplayerModule">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\UnityEngine.MultiplayerModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.ParticleSystemModule">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\UnityEngine.ParticleSystemModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.PerformanceReportingModule">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\UnityEngine.PerformanceReportingModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.Physics2DModule">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\UnityEngine.Physics2DModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.PhysicsModule">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\UnityEngine.PhysicsModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.PropertiesModule">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\UnityEngine.PropertiesModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.RuntimeInitializeOnLoadManagerInitializerModule">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\UnityEngine.RuntimeInitializeOnLoadManagerInitializerModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.ScreenCaptureModule">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\UnityEngine.ScreenCaptureModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.ShaderVariantAnalyticsModule">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\UnityEngine.ShaderVariantAnalyticsModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.SharedInternalsModule">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\UnityEngine.SharedInternalsModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.SpriteMaskModule">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\UnityEngine.SpriteMaskModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.SpriteShapeModule">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\UnityEngine.SpriteShapeModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.StreamingModule">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\UnityEngine.StreamingModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.SubstanceModule">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\UnityEngine.SubstanceModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.SubsystemsModule">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\UnityEngine.SubsystemsModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.TerrainModule">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\UnityEngine.TerrainModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.TerrainPhysicsModule">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\UnityEngine.TerrainPhysicsModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.TextCoreFontEngineModule">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\UnityEngine.TextCoreFontEngineModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.TextCoreTextEngineModule">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\UnityEngine.TextCoreTextEngineModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.TextRenderingModule">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\UnityEngine.TextRenderingModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.TilemapModule">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\UnityEngine.TilemapModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.TLSModule">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\UnityEngine.TLSModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UI">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\UnityEngine.UI.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UIElementsModule">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\UnityEngine.UIElementsModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UIModule">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\UnityEngine.UIModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UmbraModule">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\UnityEngine.UmbraModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UnityAnalyticsCommonModule">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\UnityEngine.UnityAnalyticsCommonModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UnityAnalyticsModule">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\UnityEngine.UnityAnalyticsModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UnityConnectModule">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\UnityEngine.UnityConnectModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UnityCurlModule">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\UnityEngine.UnityCurlModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UnityTestProtocolModule">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\UnityEngine.UnityTestProtocolModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UnityWebRequestAssetBundleModule">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\UnityEngine.UnityWebRequestAssetBundleModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UnityWebRequestAudioModule">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\UnityEngine.UnityWebRequestAudioModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UnityWebRequestModule">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\UnityEngine.UnityWebRequestModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UnityWebRequestTextureModule">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\UnityEngine.UnityWebRequestTextureModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UnityWebRequestWWWModule">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\UnityEngine.UnityWebRequestWWWModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.VehiclesModule">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\UnityEngine.VehiclesModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.VFXModule">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\UnityEngine.VFXModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.VideoModule">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\UnityEngine.VideoModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.VirtualTexturingModule">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\UnityEngine.VirtualTexturingModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.VRModule">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\UnityEngine.VRModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.WindModule">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\UnityEngine.WindModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.XRModule">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\UnityEngine.XRModule.dll</HintPath>
		</Reference>
		<Reference Include="__Generated">
			<HintPath>..\..\..\Desktop\fnaf-online-0.9.6-alpha\BepInEx\interop\__Generated.dll</HintPath>
		</Reference>
	</ItemGroup>
</Project>
